import { opportunities, SOURCE, REVIEW_DATE, filterOpportunities, parseSaved, escapeHtml as e, createBrief } from './data.js';
const $=s=>document.querySelector(s);
let storageAvailable=true;
function read(key){try{return localStorage.getItem(key);}catch{storageAvailable=false;return null;}}
function write(key,value){try{localStorage.setItem(key,value);return true;}catch{storageAvailable=false;return false;}}
let language=read('lp-language')==='en'?'en':'es', saved=parseSaved(read('lp-saved')),topic='all',format='all',savedOnly=false,activeItem=null,toastTimer;
const dictionary={
 es:{radar:'Radar',saved:'Guardadas',about:'El proyecto',account:'Mi cuenta',workspace:'CREATOR WORKSPACE',headline:'Tu próximo vídeo<br>empieza aquí.',intro:'De la información oficial a una idea que puedes grabar. Explora enfoques, consulta la evidencia y prepara tu contenido.',focus:'EN EL RADAR',release:'19 noviembre · 2026',platforms:'PS5 · Xbox Series X|S',official:'Consultar anuncio oficial ↗',editorial:'Selección editorial',reviewed:'Fuentes revisadas: 5 oct 2026',method:'Cómo seleccionamos las ideas',opportunities:'Oportunidades para crear',all:'Todas',launch:'Lanzamiento',platformLabel:'Plataformas',analysis:'Análisis',emptyTitle:'Todavía no hay ideas aquí.',emptyText:'Prueba otros filtros o guarda una oportunidad desde el Radar.',reset:'Volver a todas',workflow:'DE LA IDEA AL VÍDEO',workflowTitle:'Un buen enfoque.<br>Una fuente clara.',step1:'Elige una pregunta',step1copy:'Empieza por lo que tu audiencia necesita entender.',step2:'Comprueba la fuente',step2copy:'Separa hechos, interpretación y lo que aún no sabemos.',step3:'Hazlo tuyo',step3copy:'Adapta el brief a tu voz y añade tu propio análisis.',next:'LO QUE VIENE',nextTitle:'De señales a oportunidades.',nextCopy:'Estamos preparando medición de tendencias, alertas y actualización automática. Esta beta contiene ideas revisadas manualmente.',roadmap:'Ver el plan de LaunchPulse',localNote:'Tus ideas guardadas se conservan en este navegador.',disclaimer:'Proyecto independiente. Sin afiliación con Rockstar Games o Take-Two Interactive.',privacy:'Privacidad de esta beta',search:'Buscar tema o enfoque…',allFormats:'Todos los formatos',short:'Short / TikTok',video:'Vídeo largo',guide:'Guía / SEO',open:'Abrir brief',save:'Guardar idea',remove:'Quitar de guardadas',editorialTag:'Idea editorial',ideas:'ideas',evidence:'Lo que respalda la fuente',angle:'Enfoque propuesto',titles:'5 títulos para adaptar',hooks:'3 hooks para empezar',outline:'Estructura sugerida',copy:'Copiar brief',download:'Descargar brief',copied:'Brief copiado',savedToast:'Idea guardada en este navegador',removedToast:'Idea eliminada de guardadas',storageError:'No se pudo guardar. Esta sesión conservará la idea mientras la página siga abierta.',close:'Cerrar'},
 en:{radar:'Radar',saved:'Saved',about:'The project',account:'My account',workspace:'CREATOR WORKSPACE',headline:'Your next video<br>starts here.',intro:'Turn official information into an idea you can record. Explore angles, check the evidence and prepare your content.',focus:'ON THE RADAR',release:'November 19 · 2026',platforms:'PS5 · Xbox Series X|S',official:'Check the official announcement ↗',editorial:'Editorial selection',reviewed:'Sources reviewed: Oct 5, 2026',method:'How we select ideas',opportunities:'Opportunities to create',all:'All ideas',launch:'Launch',platformLabel:'Platforms',analysis:'Analysis',emptyTitle:'No ideas here yet.',emptyText:'Try other filters or save an opportunity from the Radar.',reset:'Back to all',workflow:'FROM IDEA TO VIDEO',workflowTitle:'A good angle.<br>A clear source.',step1:'Choose a question',step1copy:'Start with what your audience needs to understand.',step2:'Check the source',step2copy:'Separate facts, interpretation and what is still unknown.',step3:'Make it yours',step3copy:'Adapt the brief to your voice and add your own analysis.',next:'COMING NEXT',nextTitle:'From signals to opportunities.',nextCopy:'We are preparing trend measurement, alerts and automatic updates. This beta contains manually reviewed ideas.',roadmap:'See the LaunchPulse plan',localNote:'Your saved ideas stay in this browser.',disclaimer:'Independent project. Not affiliated with Rockstar Games or Take-Two Interactive.',privacy:'Beta privacy',search:'Search a topic or angle…',allFormats:'All formats',short:'Short / TikTok',video:'Long video',guide:'Guide / SEO',open:'Open brief',save:'Save idea',remove:'Remove saved idea',editorialTag:'Editorial idea',ideas:'ideas',evidence:'What the source supports',angle:'Suggested angle',titles:'5 titles to adapt',hooks:'3 opening hooks',outline:'Suggested outline',copy:'Copy brief',download:'Download brief',copied:'Brief copied',savedToast:'Idea saved in this browser',removedToast:'Idea removed from saved',storageError:'Could not save. This session will keep the idea while the page stays open.',close:'Close'}
};
const tr=key=>dictionary[language][key];
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function render(){
 const items=filterOpportunities(opportunities,{language,query:$('#search').value,topic,format,savedOnly,saved});
 $('#saved-count').textContent=saved.length;$('#result-count').textContent=`${items.length} ${tr('ideas')}`;$('#list-title').textContent=savedOnly?tr('saved'):tr('opportunities');
 $('#empty').hidden=items.length>0;
 $('#cards').innerHTML=items.map(item=>{const x=item[language],on=saved.includes(item.id);return `<article class="card"><div class="card-meta"><span class="topic-tag">${e(tr(item.topic==='platforms'?'platformLabel':item.topic))}</span><button class="save-button" data-save="${item.id}" aria-pressed="${on}" aria-label="${e(on?tr('remove'):tr('save'))}: ${e(x.title)}">${on?'★':'☆'}</button></div><h3>${e(x.title)}</h3><p class="card-description">${e(x.summary)}</p><div class="card-bottom"><div class="card-labels"><span>${e(tr(item.format))}</span><span>${e(tr('editorialTag'))}</span></div><div class="card-footer"><span class="card-source">Rockstar Games</span><button class="open-brief" data-open="${item.id}">${e(tr('open'))}</button></div></div></article>`;}).join('');
}
function setLanguage(lang){language=lang;write('lp-language',lang);document.documentElement.lang=lang;$('#language').value=lang;
 document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(key==='headline'||key==='workflowTitle')el.innerHTML=tr(key);else el.textContent=tr(key);});
 $('#search').placeholder=tr('search');$('#search').ariaLabel=tr('search');$('#format').ariaLabel=tr('allFormats');
 Array.from($('#format').options).forEach(option=>option.textContent=tr(option.value==='all'?'allFormats':option.value));
 document.querySelectorAll('.close').forEach(button=>button.ariaLabel=tr('close'));
 render();if(activeItem&&$('#detail-dialog').open)renderDetail(activeItem);
}
function toggleSave(id){if(!opportunities.some(x=>x.id===id))return;const existed=saved.includes(id);saved=existed?saved.filter(x=>x!==id):[...saved,id];const stored=write('lp-saved',JSON.stringify(saved));render();if(activeItem&&$('#detail-dialog').open)renderDetail(activeItem);toast(stored?tr(existed?'removedToast':'savedToast'):tr('storageError'));}
function renderDetail(item){const x=item[language];$('#detail-body').innerHTML=`<h2 id="detail-title">${e(x.title)}</h2><p>${e(x.summary)}</p><div class="evidence"><strong>${e(tr('evidence'))}</strong><p>${e(x.evidence)}</p><a href="${SOURCE.url}" target="_blank" rel="noopener noreferrer">${e(SOURCE.name)} ↗</a><p class="mono">${REVIEW_DATE}</p></div><p class="caution">${e(x.caveat)}</p><h3>${e(tr('angle'))}</h3><p>${e(x.angle)}</p><h3>${e(tr('titles'))}</h3><ol>${x.titles.map(t=>`<li>${e(t)}</li>`).join('')}</ol><h3>${e(tr('hooks'))}</h3><ul>${x.hooks.map(t=>`<li>${e(t)}</li>`).join('')}</ul><h3>${e(tr('outline'))}</h3><ol>${x.outline.map(t=>`<li>${e(t)}</li>`).join('')}</ol><h3>Keywords</h3><p>${x.keywords.map(e).join(' · ')}</p><div class="dialog-actions"><button class="primary" data-copy>${e(tr('copy'))}</button><button class="secondary" data-download>${e(tr('download'))}</button><button class="secondary" data-save="${item.id}" aria-pressed="${saved.includes(item.id)}">${e(tr(saved.includes(item.id)?'remove':'save'))}</button></div>`;}
function detail(id){const item=opportunities.find(x=>x.id===id);if(!item)return;activeItem=item;renderDetail(item);$('#detail-dialog').showModal();$('#detail-dialog').scrollTop=0;}
function info(title,html){$('#info-body').innerHTML=`<h2 id="info-title">${e(title)}</h2>${html}`;$('#info-dialog').showModal();}
function about(){info(language==='es'?'Una ventaja empieza con una buena pregunta.':'An advantage starts with a good question.',language==='es'?`<p>LaunchPulse ayuda a creadores a convertir información de grandes lanzamientos en contenido original. Empezamos con GTA VI, en español e inglés.</p><h3>Disponible en esta beta</h3><p>Seis briefs editoriales con fuentes, búsqueda, filtros, ideas guardadas y exportación. No requiere registro.</p><h3>La siguiente etapa</h3><p>Medición de señales, historial, cuentas y alertas. Después: Ready Check para jugadores, afiliados aprobados y Discovery Radar.</p><div class="intro-price"><div class="price-box">Free<strong>US$0</strong><p>La beta editorial actual es gratuita.</p></div><div class="price-box">Creator · propuesta<strong>US$19/mes</strong><p>Suscripción prevista. No está a la venta todavía.</p></div></div><p>Los precios y funciones de pago se validarán antes de activar cobros.</p>`:`<p>LaunchPulse helps creators turn information around major game launches into original content. We are starting with GTA VI, in English and Spanish.</p><h3>Available in this beta</h3><p>Six sourced editorial briefs, search, filters, saved ideas and export. No registration required.</p><h3>Next stage</h3><p>Signal measurement, history, accounts and alerts. Later: Ready Check for players, approved affiliate links and Discovery Radar.</p><div class="intro-price"><div class="price-box">Free<strong>US$0</strong><p>The current editorial beta is free.</p></div><div class="price-box">Creator · proposed<strong>US$19/month</strong><p>Planned subscription. Not on sale yet.</p></div></div><p>Pricing and paid features will be validated before payments are enabled.</p>`);}
document.addEventListener('click',async event=>{
 const save=event.target.closest('[data-save]');if(save){toggleSave(save.dataset.save);return;}
 const open=event.target.closest('[data-open]');if(open){detail(open.dataset.open);return;}
 if(event.target.closest('[data-copy]')&&activeItem){try{await navigator.clipboard.writeText(createBrief(activeItem,language));toast(tr('copied'));}catch{toast(language==='es'?'No se pudo copiar. Usa Descargar brief.':'Copy unavailable. Use Download brief.');}return;}
 if(event.target.closest('[data-download]')&&activeItem){const url=URL.createObjectURL(new Blob([createBrief(activeItem,language)],{type:'text/markdown;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`launchpulse-${activeItem.id}-${language}.md`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{savedOnly=button.dataset.view==='saved';document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===button));render();}));
document.querySelectorAll('[data-topic]').forEach(button=>button.addEventListener('click',()=>{topic=button.dataset.topic;document.querySelectorAll('[data-topic]').forEach(x=>{x.classList.toggle('selected',x===button);x.setAttribute('aria-pressed',String(x===button));});render();}));
$('#search').addEventListener('input',render);$('#format').addEventListener('change',event=>{format=event.target.value;render();});$('#language').addEventListener('change',event=>setLanguage(event.target.value));
$('#reset-filters').addEventListener('click',()=>{$('#search').value='';$('#format').value='all';format='all';document.querySelector('[data-topic="all"]').click();document.querySelector('[data-view="all"]').click();});
document.querySelectorAll('dialog .close').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}}));
$('#about-button').addEventListener('click',about);$('#roadmap-button').addEventListener('click',about);
$('#method-button').addEventListener('click',()=>info(language==='es'?'Ideas con contexto, sin métricas inventadas.':'Contextual ideas, without invented metrics.',language==='es'?`<p>Seleccionamos preguntas que se pueden convertir en una explicación útil usando fuentes oficiales. Los títulos, hooks y enfoques son propuestas editoriales de LaunchPulse.</p><ul><li>Las fuentes se revisaron el 5 de octubre de 2026.</li><li>Esta selección no se actualiza automáticamente.</li><li>No medimos todavía crecimiento, saturación, búsquedas ni competencia por idioma.</li><li>No asignamos un Opportunity Score hasta contar con señales suficientes y un método comprobable.</li></ul><p>Comprueba siempre la fuente antes de publicar. Una idea editorial no garantiza audiencia ni ingresos.</p>`:`<p>We select questions that can become useful explanations based on official sources. Titles, hooks and angles are editorial suggestions authored by LaunchPulse.</p><ul><li>Sources were reviewed on October 5, 2026.</li><li>This selection does not refresh automatically.</li><li>Growth, saturation, search volume and language competition are not measured yet.</li><li>We will introduce an Opportunity Score only with sufficient signals and a verifiable method.</li></ul><p>Check the source before publishing. An editorial idea does not guarantee views or income.</p>`));
$('#privacy-button').addEventListener('click',()=>info(language==='es'?'Privacidad de esta beta':'Beta privacy',language==='es'?`<p>Esta versión no pide tu correo, no procesa pagos y no incorpora analítica publicitaria. Guarda en tu navegador únicamente el idioma y los identificadores de las ideas favoritas.</p><p>El alojamiento puede registrar datos técnicos necesarios para servir la página, como solicitudes y direcciones IP. Los enlaces externos te llevan a sitios con sus propias políticas.</p><button class="secondary" id="clear-local">Borrar preferencias e ideas locales</button>`:`<p>This version does not ask for your email, process payments or include advertising analytics. It stores only your language preference and saved idea identifiers in this browser.</p><p>The hosting provider may log technical data needed to serve the page, including requests and IP addresses. External links lead to sites with their own policies.</p><button class="secondary" id="clear-local">Clear local preferences and saved ideas</button>`));
$('#info-body').addEventListener('click',event=>{if(event.target.id==='clear-local'){try{localStorage.removeItem('lp-language');localStorage.removeItem('lp-saved');saved=[];render();toast(language==='es'?'Datos locales borrados':'Local data cleared');}catch{toast(tr('storageError'));}}});
$('#account-button').addEventListener('click',()=>info(language==='es'?'Tu espacio, por ahora en este navegador':'Your workspace, currently in this browser',language==='es'?`<p>Puedes consultar y guardar todas las ideas de esta beta sin registrarte.</p><p>Las cuentas y la sincronización entre dispositivos están en preparación. No estamos recogiendo correos ni contraseñas en esta versión.</p><button class="primary" id="go-saved">Ver mis ideas guardadas</button>`:`<p>You can browse and save all ideas in this beta without registering.</p><p>Accounts and cross-device sync are being prepared. This version does not collect emails or passwords.</p><button class="primary" id="go-saved">View saved ideas</button>`));
$('#info-body').addEventListener('click',event=>{if(event.target.id==='go-saved'){$('#info-dialog').close();document.querySelector('[data-view="saved"]').click();}});
setLanguage(language);
if(!storageAvailable)toast(tr('storageError'));
