export const REVIEW_DATE = '2026-10-05';
export const SOURCE = { name: 'Rockstar Games · GTA VI', url: 'https://www.rockstargames.com/VI' };
// These are authored editorial briefs, not measured trends or generated demand scores.
export const opportunities = [
 {id:'launch-date',topic:'launch',format:'short',es:{
 title:'La fecha, sin el ruido',summary:'Un Short con la fecha oficial y una forma sencilla de comprobar cambios.',
 evidence:'La web oficial anuncia el 19 de noviembre de 2026.',caveat:'Es la fecha publicada en la revisión. Comprueba el anuncio antes de grabar; puede cambiar.',
 titles:['GTA VI: la fecha oficial, explicada en 30 segundos','Cómo comprobar la fecha de GTA VI sin caer en rumores','Antes de compartir otra fecha de GTA VI, mira esto','Tu referencia para el lanzamiento de GTA VI','GTA VI: qué dice hoy la fuente oficial'],
 hooks:['¿Has visto otra fecha para GTA VI? Empieza por la fuente.','Una captura sin enlace no basta para confirmar un lanzamiento.','Aquí tienes el anuncio que debes revisar antes de hacer planes.'],
 outline:['Abre con la pregunta sobre la fecha.','Indica la fecha publicada y cuándo la comprobaste.','Muestra cómo llegar a la fuente oficial.','Cierra recordando que conviene revisarla antes de comprar o reservar tiempo.'],keywords:['GTA VI fecha','GTA 6 lanzamiento','fecha oficial'],angle:'Claridad antes que urgencia. Una pieza breve y fácil de actualizar.'},en:{
 title:'The date, without the noise',summary:'A Short explaining the official date and how viewers can check for changes.',
 evidence:'The official website announces November 19, 2026.',caveat:'This is the date published when reviewed. Check the announcement before recording; it may change.',
 titles:['GTA VI: the official date in 30 seconds','How to verify the GTA VI release date','Before you share another GTA VI date, check this','Your source for the GTA VI launch date','GTA VI: what the official source says'],
 hooks:['Seen another GTA VI date? Start with the source.','A screenshot without a link does not confirm a release date.','Check this announcement before you make plans.'],
 outline:['Open with the release-date question.','State the published date and when you checked it.','Show how to reach the official source.','Remind viewers to check again before buying or booking time off.'],keywords:['GTA VI release date','GTA 6 launch','official date'],angle:'Clarity over urgency. A short piece you can update easily.'}},
 {id:'platforms',topic:'platforms',format:'video',es:{title:'¿En qué plataformas está anunciado?',summary:'Una explicación útil para quien tiene consola, PC o está pensando en comprar.',evidence:'La página oficial enumera PlayStation 5 y Xbox Series X|S.',caveat:'No extrapoles rendimiento, resolución o futuras versiones a partir de esta lista.',titles:['GTA VI: plataformas anunciadas y dudas pendientes','¿Tu plataforma aparece en la web de GTA VI?','Antes de comprar una consola para GTA VI','GTA VI en PS5 y Xbox: qué está anunciado','Lo que la lista de plataformas sí nos dice'],hooks:['Antes de gastar, separa lo anunciado de lo que suponemos.','Que una plataforma esté anunciada no responde todas las preguntas.','Empecemos con dos nombres que sí aparecen en la web oficial.'],outline:['Presenta la duda del comprador.','Explica la lista oficial de plataformas.','Separa compatibilidad anunciada de rendimiento no verificado.','Deja una lista de preguntas que el espectador debe resolver antes de comprar.'],keywords:['GTA VI plataformas','GTA VI PS5','GTA VI Xbox'],angle:'Una guía neutral, sin recomendar compras basadas en especificaciones no confirmadas.'},en:{title:'Which platforms are announced?',summary:'A useful explainer for console owners, PC players and prospective buyers.',evidence:'The official page lists PlayStation 5 and Xbox Series X|S.',caveat:'Do not infer performance, resolution or future versions from this list.',titles:['GTA VI: announced platforms and open questions','Is your platform on the official GTA VI page?','Before buying a console for GTA VI','GTA VI on PS5 and Xbox: what is announced','What the platform list actually tells us'],hooks:['Before you spend, separate announcements from assumptions.','An announced platform does not answer every question.','Start with the two names on the official page.'],outline:['Introduce the buyer’s question.','Explain the official platform list.','Separate announced support from unverified performance.','List questions viewers should answer before buying.'],keywords:['GTA VI platforms','GTA VI PS5','GTA VI Xbox'],angle:'A neutral guide without recommendations based on unconfirmed specifications.'}},
 {id:'trailer-analysis',topic:'analysis',format:'video',es:{title:'Tráiler: observación o interpretación',summary:'Convierte una reacción en un análisis que distingue lo visible de tus hipótesis.',evidence:'Rockstar enlaza los tráileres de GTA VI desde su página oficial.',caveat:'Una escena de un tráiler no demuestra por sí sola una mecánica jugable. No reutilices material sin revisar los permisos.',titles:['GTA VI: lo que vemos y lo que estamos suponiendo','Cómo analizar un tráiler de GTA VI con criterio','Tres preguntas para revisar el tráiler de GTA VI','GTA VI: observación, interpretación y dudas','El detalle no es la confirmación'],hooks:['¿Esto está confirmado o lo estamos interpretando?','Paremos un momento: una escena no es una promesa jugable.','Vamos a separar lo que se ve de lo que imaginamos.'],outline:['Elige una pregunta concreta y consulta el tráiler oficial.','Describe solo la observación comprobable.','Presenta tu interpretación como hipótesis.','Explica qué evidencia faltaría para confirmarla.'],keywords:['GTA VI análisis','GTA VI tráiler','análisis de videojuegos'],angle:'La propuesta es el método de análisis; tú eliges las escenas y aportas una lectura propia.'},en:{title:'Trailer: observation or interpretation?',summary:'Turn a reaction into analysis that separates visible details from your hypotheses.',evidence:'Rockstar links GTA VI trailers from its official page.',caveat:'A trailer scene alone does not establish a gameplay mechanic. Check permissions before reusing footage.',titles:['GTA VI: what we see versus what we assume','How to analyse a GTA VI trailer thoughtfully','Three questions for a GTA VI trailer breakdown','GTA VI: observations, interpretations and questions','A detail is not a confirmation'],hooks:['Is this confirmed, or are we interpreting it?','Pause: a scene is not a gameplay promise.','Let’s separate what we see from what we imagine.'],outline:['Choose one question and consult the official trailer.','Describe only the observable detail.','Present your interpretation as a hypothesis.','Explain what evidence would confirm it.'],keywords:['GTA VI analysis','GTA VI trailer','game analysis'],angle:'The opportunity is the analysis method; choose your own scenes and add original commentary.'}},
 {id:'rumor-check',topic:'analysis',format:'short',es:{title:'Antes de compartir ese rumor',summary:'Enseña a tu audiencia a rastrear una afirmación hasta su origen.',evidence:'La página oficial de GTA VI ofrece un punto de partida para contrastar anuncios.',caveat:'Que una afirmación no figure allí no demuestra que sea falsa. Etiquétala como no verificada.',titles:['GTA VI: tres pasos antes de compartir un rumor','¿Noticia o rumor? Comprueba la fuente','Cómo rastrear un anuncio de GTA VI','No confundas una captura con una confirmación','El filtro que uso para las noticias de GTA VI'],hooks:['Antes de compartirlo, ¿puedes encontrar la fuente original?','Que lo repitan diez cuentas no lo convierte en oficial.','Hay una diferencia entre falso y no confirmado.'],outline:['Plantea una afirmación hipotética sin difundir filtraciones.','Busca origen, fecha y contexto.','Contrasta con la fuente oficial.','Clasifica el resultado: confirmado, interpretación o no verificado.'],keywords:['GTA VI rumores','GTA VI noticias','verificar fuentes'],angle:'Una pieza educativa reutilizable, sin amplificar rumores específicos.'},en:{title:'Before you share that rumour',summary:'Teach your audience to trace a claim back to its original source.',evidence:'The official GTA VI page is a starting point for checking announcements.',caveat:'A claim missing from this page is not automatically false. Label it unverified.',titles:['GTA VI: three checks before sharing a rumour','News or rumour? Check the source','How to trace a GTA VI announcement','A screenshot is not a confirmation','My filter for GTA VI news'],hooks:['Before sharing, can you find the original source?','Ten accounts repeating a claim does not make it official.','False and unconfirmed are different things.'],outline:['Use a hypothetical claim without spreading leaks.','Find its origin, date and context.','Compare it with official information.','Classify it as confirmed, interpretation or unverified.'],keywords:['GTA VI rumours','GTA VI news','source checking'],angle:'A reusable educational piece without amplifying specific rumours.'}},
 {id:'preparation-guide',topic:'launch',format:'guide',es:{title:'Una checklist antes del lanzamiento',summary:'Un recurso que tus seguidores pueden guardar y volver a consultar.',evidence:'El anuncio oficial permite comprobar fecha y plataformas antes de planificar.',caveat:'No inventes requisitos de almacenamiento, descarga, suscripciones o rendimiento. Déjalos pendientes de confirmar.',titles:['Checklist de GTA VI: qué comprobar antes del lanzamiento','Organiza tu preparación para GTA VI','GTA VI: una lista útil sin compras impulsivas','Qué revisar antes de reservar GTA VI','Tu lista de preguntas para el lanzamiento'],hooks:['No necesitas comprarlo todo: primero comprueba esto.','Guarda esta lista y actualízala cuando haya información oficial.','Prepararte empieza por saber qué falta confirmar.'],outline:['Anota fecha y plataforma desde la fuente.','Revisa las condiciones del vendedor que elijas.','Señala los requisitos aún no comprobados.','Añade fecha de revisión y actualiza la guía cuando cambie la información.'],keywords:['GTA VI preparación','GTA VI checklist','GTA VI guía'],angle:'Utilidad duradera: una lista editable y transparente sobre lo que falta saber.'},en:{title:'A pre-launch checklist',summary:'A resource your followers can save and revisit.',evidence:'The official announcement lets readers check the date and platforms before planning.',caveat:'Do not invent storage, download, subscription or performance requirements. Mark them as awaiting confirmation.',titles:['GTA VI checklist: what to check before launch','Organise your GTA VI preparations','A useful GTA VI list without impulse purchases','What to check before pre-ordering GTA VI','Your questions for the GTA VI launch'],hooks:['You do not need to buy everything: check this first.','Save this list and update it when official details change.','Preparation starts with knowing what remains unconfirmed.'],outline:['Record the date and platform from the source.','Review the conditions of your chosen retailer.','Flag requirements you have not verified.','Date the guide and update it as information changes.'],keywords:['GTA VI preparation','GTA VI checklist','GTA VI guide'],angle:'Lasting usefulness: an editable checklist that is clear about what is still unknown.'}},
 {id:'bilingual-brief',topic:'analysis',format:'short',es:{title:'Un anuncio, dos audiencias',summary:'Adapta una explicación oficial del inglés al español con contexto propio.',evidence:'La web oficial es la referencia del anuncio; este brief propone una adaptación editorial.',caveat:'No afirmamos que exista menor competencia en español: todavía no medimos cobertura ni demanda por idioma.',titles:['GTA VI explicado en español, con la fuente a mano','Del anuncio a una explicación clara de GTA VI','Cómo entender una noticia de GTA VI en inglés','GTA VI: el contexto detrás del titular','Una noticia de GTA VI, explicada sin exagerar'],hooks:['El titular en inglés necesita un poco de contexto.','Traducir palabra por palabra no siempre aclara la noticia.','Vamos a explicar qué significa, y qué no significa.'],outline:['Elige un anuncio oficial y enlázalo.','Identifica una duda concreta de tu audiencia.','Explica con tus palabras, manteniendo las limitaciones originales.','Distingue la traducción de tu comentario personal.'],keywords:['GTA VI español','GTA VI explicado','noticias gaming'],angle:'Adaptación cultural y claridad; no una promesa de ventaja frente a otros creadores.'},en:{title:'One announcement, two audiences',summary:'Adapt an official English-language explanation for Spanish-speaking viewers.',evidence:'The official page is the announcement reference; this brief suggests an editorial adaptation.',caveat:'We do not claim lower competition in Spanish. Coverage and demand by language are not yet measured.',titles:['GTA VI explained with the source at hand','From announcement to a clear GTA VI explainer','Helping viewers understand GTA VI news in English','GTA VI: the context behind the headline','Explain a GTA VI announcement without exaggerating'],hooks:['That English headline needs a little context.','Word-for-word translation does not always clarify the news.','Let’s explain what this means, and what it does not.'],outline:['Choose and link an official announcement.','Identify a specific question your viewers have.','Explain it in your own words while preserving its limitations.','Separate translation from personal commentary.'],keywords:['GTA VI Spanish','GTA VI explained','gaming news'],angle:'Cultural adaptation and clarity, without promising a competitive advantage.'}}
];
export function normalize(value) { return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(); }
export function filterOpportunities(items, {language='es',query='',topic='all',format='all',savedOnly=false,saved=[]}={}) {
 const q=normalize(query.trim());
 return items.filter(item=>(topic==='all'||item.topic===topic)&&(format==='all'||item.format===format)&&(!savedOnly||saved.includes(item.id))&&(!q||normalize([item[language].title,item[language].summary,...item[language].keywords].join(' ')).includes(q)));
}
export function parseSaved(raw) { try { const ids=JSON.parse(raw); return Array.isArray(ids)?[...new Set(ids.filter(id=>opportunities.some(item=>item.id===id)))]:[]; } catch {return [];} }
export function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
export function createBrief(item,language='es') {
 const x=item[language], en=language==='en';
 return `# ${x.title}\n\nLaunchPulse · ${en?'Editorial brief — not a measured trend':'Brief editorial — no es una tendencia medida'}\n${en?'Source':'Fuente'}: ${SOURCE.url}\n${en?'Reviewed':'Revisado'}: ${REVIEW_DATE}\n\n${x.evidence}\n${x.caveat}\n\n## ${en?'Angle':'Enfoque'}\n${x.angle}\n\n## ${en?'Titles':'Títulos'}\n${x.titles.map(t=>'- '+t).join('\n')}\n\n## Hooks\n${x.hooks.map(t=>'- '+t).join('\n')}\n\n## ${en?'Outline':'Estructura'}\n${x.outline.map((t,i)=>`${i+1}. ${t}`).join('\n')}\n\n## Keywords\n${x.keywords.join(', ')}\n`;
}
